project:
  type: website

website:
  title: "DistrictView"
  navbar: false
  sidebar: false
  
format:
  html:
    theme: slate
    css: styles.css
    toc: false
    fontcolor: white
    fontsize: 1.5em