project:
  type: website

website:
  title: "DistrictView"
  navbar: 
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - funders.qmd
      - researchteam.qmd 
  sidebar: false
  
format:
  html:
    theme: slate
    css: styles.css
    toc: false
    fontcolor: white
    fontsize: 1.5em